import React from 'react';
import PropTypes from 'prop-types';

const QuadrantDescription = ({ quadrant }) => {
  let quadrantInfo = '';
  if(quadrant === 'North') quadrantInfo = 'North Portland is known for its quirky neighborhoods like Kenton and Arbor Lodge. North Portland is the most up and coming area in the city and has been for the past 10 years. Neighborhoods that used to be abandoned and condemned are now some of the more desirable ares to live on the East side.  I even heard that the ex mayor of Portland, Sam Adams, lives in Kenton. One of the downsides of North Portland is the amount of skinnies built in the area. Older homes have been purchased and torn down, the lots divided and smaller - skinny- homes built. There is a large mix of old and new homes in North Portland due to the many infill lots. One notable neighborhood is New Columbia, this area was redone in 2001 to create a community that consists of single family homes, condos, town houses and green spaces.  was the cities effort to revitalize the Columbia neighborhood that was for years run down and considered the Portland projects. Overall this project and community imp';
  if(quadrant === 'Northeast') quadrantInfo = 'Northeast Portland is known for its gorgeous neighborhoods, such as Alameda Ridge, Grant Park and Hollywood. Homes run on average $228 per square feet and are on the market for an average 9 days. Northeast Portland is the largest of the quadrants and is home to many landmarks such as Lloyd Center and the Airport. Lloyd Center was Oregon\'s largest open air shopping center when is was built in 1960. It is still the largest mall in Oregon, but is no longer open air, it was closed in the early 1990\'s. It is a central hub in NE Portland and is accessible by Tri-Met (Portland Public transit system) and is extremely walk-able and bicycle friendly. The hottest areas in Northeast, as far as real estate is concerned, are Sabin and King, check out www.sabinpdx.org for more neighborhood info. Lots in these neighborhoods have risen in price from a few years ago being around $130,000 to today being $350,000, this would be for a tear down home, so really the price is just for the land. One neighborhood in Northeast that has faced some challenges is the Cully neighborhood, residents in this area are working hard to revitalize the community and hosted the largest one day clean up in the entire city of Portland for several years in a row. Northeast does extend all the way to Fairview and Troutdale, they are further East toward Mt.Hood.';
  if(quadrant === 'Northwest') quadrantInfo = 'Northwest Portland is known for its Pearl district. The Pearl is loaded with high end shops, restaurants and condos and was a warehouse district less than 20 years ago. City planners from around the world come to NW Portland to study the Pearl district as it is known world wide for it\'s livability. Average price per square foot is $418 and homes are on the market for around 12 days. Another notable area in NW is is Forest Heights which is home to Forest Park, the largest park in the United States. Forest Park has many beautiful hiking trails and countless acres of native Oregon floral and fauna. NW Portland is a shopping mecca and boasts Portland\'s new streetcar system. It is also part of fare-less square, Portland\'s free public transportation system.';
  if(quadrant === 'South') quadrantInfo = 'According to Mikey Romay, this is a thing';
  if(quadrant === 'Southeast') quadrantInfo = 'Southeast Portland is known for its eclectic neighborhoods, like Hawthorne and Belmont, and local shops. Homes run $214 per square foot on average and are staying on the market for about 8 days before selling. Southeast is home to gorgeous neighborhoods with large old Portland 1920\'s bungalows and Spanish style homes like Ladds Addition and Laurelhurst. Laurelhurst is a very popular area that is close to Tri-Met, parks, restaurants and local boutiques and is close in SE Portland. Prices of homes in Laurelhurst have out preformed the market over the years even with the market changes. Southeast also has many multi-family properties that include plexes and apartment buildings. Southeast has the most available inventory of all the quadrants and a wide range of properties and prices. There are some areas of SE that are struggling, Lents is a neighborhood that is part of Urban renewal, check out www.pdc.us for more info. Southeast Portland extends out to Gresham.';
  if(quadrant === 'Southwest') quadrantInfo = 'Southwest is known as Portland\'s cultural center, with the Art Museum, gorgeous parks and public art. Home is SW are SElling for on average $247 per square foot. Homes in SW are typically on the market for 15 days. Southwest Portland is the heart of the city and includes, Pioneer Courthouse Square known as Portland\'s living room, check out www.thesquarepdx.org for info. This was once the Portland Hotel and later a parking lot for Meier and Frank and now is a city block dedicated to Portland\'s lifestyle. It is the heart of the Tri-Met system, including the Max and buses, and the information center with maps and info about the history of the city. SW is home to both the best High schools in the city, Lincoln and Riverdale. Southwest is also home to Lewis and Clark College, which is one of the best liberal arts schools in the nation, it is also in a gorgeous setting surrounded by trees and lots of roses. Portland\'s city flower is the rose.';

  return (
    <p>{quadrantInfo}</p>);
};

QuadrantDescription.propTypes = {
  quadrant: PropTypes.string
};

export default QuadrantDescription;
